approjet4_booking_home:
    path:    /
    defaults: { _controller: APProjet4BookingBundle:Booking:home}

## Accueil
approjet4_booking_index:
    path:     /events
    defaults: { _controller: APProjet4BookingBundle:Booking:index}
       
## Page 1 - Date de visite et type de billet (Journée/Demi-journée)    
approjet4_booking_selectDate:
    path:    /purchase/{id}
    defaults: { _controller: APProjet4BookingBundle:Booking:selectDate}
    
 ## Page 2 - Nombre de billets et renseignements  
approjet4_booking_contactDetails:
    path:    /details
    defaults: { _controller: APProjet4BookingBundle:Booking:contactDetails}   


