approjet4_booking_home:
    path:    /
    defaults: { _controller: APProjet4BookingBundle:Home:home}

## Accueil
approjet4_booking_index:
    path:     /events
    defaults: { _controller: APProjet4BookingBundle:Home:index}

## Changement de locale
approjet4_booking_setLocale:
    path: /locale
    defaults: { _controller: APProjet4BookingBundle:Session:setLocale}
    methods: [GET]

## Page 1 - Date de visite et type de billet (Journée/Demi-journée)    
approjet4_booking_selectDate:
    path:    /purchase/{id}
    defaults: { _controller: APProjet4BookingBundle:Booking:showSelectDate , format: html}
    requirements:
        id: \d+
    
## Vérification max 1000 tickets ( Ajax )
approjet4_booking_max_booking_ajax:
    path : /max-booking
    defaults: { _controller: APProjet4BookingBundle:Booking:max}
    methods: [GET]

## Submit ( Ajax )
approjet4_booking_pick_a_date:
    path:    /save_date
    defaults: {_controller: APProjet4BookingBundle:Booking:saveDate}
    methods: [POST]

 ## Page 2 - Nombre de billets et renseignements  
approjet4_booking_showContactDetails:
    path:    /details
    defaults: { _controller: APProjet4BookingBundle:Booking:showContactDetails}
    
approjet4_booking_postContactDetails:
    path:   /details/postAction
    defaults: {_controller: APProjet4BookingBundle:Booking:postContactDetails}
    methods: [POST]
    
## Page3 - Récapitulatif et Adresse Email
approjet4_booking_showRecap:
    path:   /recapitulative
    defaults: {_controller: APProjet4BookingBundle:Booking:showRecap}
    methods: [POST, GET]

approjet4_booking_postEmailAndBooking:
    path:   /recapitulative/postAction
    defaults: {_controller: APProjet4BookingBundle:Booking:postEmailAndBooking}
    methods: [POST, GET]

approjet4_booking_payment:
    path: /payment
    defaults: {_controller: APProjet4BookingBundle:Booking:ValidatePayment}
    methods: [POST, GET]
    
##Ajouter/ {orderCode}
approjet4_booking_showPayment:
    path: /paymentConfirmed/{orderCode}
    defaults: {_controller: APProjet4BookingBundle:Booking:showPayment , format: html  }
    methods: [GET]
    