## Page 0 - Accueil
approjet4_booking_home:
    path:     /home
    defaults: { _controller: APProjet4BookingBundle:Booking:index }
    
## Page 1 - Date de visite et type de billet (Journée/Demi-journée)    
approjet4_booking_newOrder:
    path:    /tickets
    defaults: {_controller: APProjet4BookingBundle:Booking:newOrder }
    
    


