ap_projet4_booking_homepage:
    path:     /
    defaults: { _controller: APProjet4BookingBundle:Booking:index }

hello_the_world:
    path:     /hello-world
    defaults: { _controller: APProjet4BookingBundle:Booking:index }