approjet4_booking_home:
    path:     /home
    defaults: { _controller: APProjet4BookingBundle:Booking:index }
    
approjet4_booking_newOrder:
    path:    /tickets
    defaults: {_controller: APProjet4BookingBundle:Booking:newOrder }
    