approjet4_booking_home:
    path:    /
    defaults: { _controller: APProjet4BookingBundle:Booking:home}

## Accueil
approjet4_booking_index:
    path:     /events
    defaults: { _controller: APProjet4BookingBundle:Booking:index}
       
## Page 1 - Date de visite et type de billet (Journée/Demi-journée)    
approjet4_booking_selectDate:
    path:    /purchase/{id}
    defaults: { _controller: APProjet4BookingBundle:Booking:selectDate}
    requirements:
        id: \d+
    
## Vérification max 1000 tickets ( Ajax )
approjet4_booking_max_booking:
    path : /max-booking
    defaults: { _controller: APProjet4BookingBundle:Booking:max}

## Submit ( Ajax )
approjet4_booking_pick_a_date:
    path:    /save_date
    defaults: {_controller: APProjet4BookingBundle:Booking:saveDate}

 ## Page 2 - Nombre de billets et renseignements  
approjet4_booking_contactDetails:
    path:    /details
    defaults: { _controller: APProjet4BookingBundle:Booking:contactDetails}

##approjet4_booking_contactDetail2:
   ## path:    /details/{id}
   ## defaults: { _controller: APProjet4BookingBundle:Booking:contactDetails}
    
## Page3 - Récapitulatif et Adresse Email
approjet4_booking_email:
    path:   /
    defaults: {_controller: APPRojet4BookingBundle:Booking:email}
