# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #    service_name:
    #        class: AppBundle\Directory\ClassName
    #        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    stripe.payment.system:
        class : APProjet4\BookingBundle\Services\StripePaymentSystem
    
    ticket.fare.system:
        class : APProjet4\BookingBundle\Services\TicketFareSystem
    
    disabled.dates.system:
        class :  APProjet4\BookingBundle\Services\DisabledDatesSystem
        arguments: ["@doctrine.orm.entity_manager"]

    control.visitdate.system:
        class : APProjet4\BookingBundle\Services\ControlVisitDateSystem
        arguments: 
            - "@disabled.dates.system"
           
    nb.and.total.system:
        class : APProjet4\BookingBundle\Services\NbAndTotalSystem