# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    booking.email.system:
        class : APProjet4\BookingBundle\Services\BookingEmailSystem
        arguments: ["@mailer", "@twig"]
    
    stripe.payment.system:
        class : APProjet4\BookingBundle\Services\StripePaymentSystem
        
