<?php

namespace APProjet4\BookingBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository {

    public static function countTicketsPerDay($orderDate) {
        $qb = $this->createQueryBuilder('t');
        $qb
                ->select('count(t.id)')
                ->leftJoin('t.booking', 'b')
                ->where('b.orderDate=:date')
                ->setParameter('date', $orderDate)
                ->andWhere('b.status>=:status')
                ->setParameter('status', Booking::STATUS_PAID);
        return $qb->getQuery()->getArrayResult();
        //renvoyer un nombre de tickets();
    }
}
