<?php

namespace APProjet4\BookingBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository {

    const HEURE_MAX = '14';

    public static function checkTime($visitDate) {
        $now = new \DateTime();

        if (($visitDate->format('Ymd') === $now->format('Ymd')) && ($now->format('H') >= self::HEURE_MAX)) {
            return true;
        } else {
            return false;
        }
    }

}
